# Generated by Django 3.2.7 on 2021-09-29 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('bullyDate', models.DateField()),
                ('anonym', models.BooleanField(default=False)),
                ('isYou', models.BooleanField(default=True)),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiWorkShop.situation')),
            ],
        ),
    ]
