# Generated by Django 3.2.7 on 2021-09-29 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiWorkShop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='createAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
