# Generated by Django 3.2.7 on 2021-09-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiWorkShop', '0002_usermessage_createat'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='status',
            field=models.NullBooleanField(),
        ),
    ]
